[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid
user=root

[program:yamong_tracepoint]
command=/ebpf/src/tracepoint/tracepoint
directory=/
autostart=true
autorestart=true
startretries=9999999
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=TERM
killasgroup=true

[program:yamong_lsm]
command=/ebpf/src/lsm/enforcement
directory=/
autostart=true
autorestart=true
startretries=9999999
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=TERM
killasgroup=true

[program:yamong_raw_tracepoint]
command=/ebpf/src/raw_tracepoint/raw_tracepoint
directory=/
autostart=true
autorestart=true
startretries=9999999
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=TERM
killasgroup=true