[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid
user=root

[program:yamong_tracepoint]
; 기존 command:
; command=/ebpf/src/tracepoint/tracepoint
command=/bin/sh -c "/ebpf/src/tracepoint/tracepoint 2>&1 | sed 's/^/[tracepoint] /'"
directory=/
autostart=true
autorestart=true
startretries=9999999
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:yamong_lsm]
; 기존 command:
; command=/ebpf/src/lsm/enforcement
command=/bin/sh -c "/ebpf/src/lsm/enforcement 2>&1 | sed 's/^/[lsm] /'"
directory=/
autostart=true
autorestart=true
startretries=9999999
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:yamong_raw_tracepoint]
; 기존 command:
; command=/ebpf/src/raw_tracepoint/raw_tracepoint
command=/bin/sh -c "/ebpf/src/raw_tracepoint/raw_tracepoint 2>&1 | sed 's/^/[raw_tracepoint] /'"
directory=/
autostart=true
autorestart=true
startretries=9999999
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
